<?php

    $lang = array(
        "lang_en" => "EN",
		"lang_bg" => "BG",
        "home" => "Home",
        "categories" => "Categories",
        "afd" => "All foods and drinks",
        "1card-in" => "From Food House restaurant you can order food for home from anywhere.",
        "2card-in" => "Address: st. Radost 3, Varna",
        "3card-in" => "Email: foodhouse@abv.bg",
        "32card-in" => "Number: 0898899888",
        "rights" => "2022 © All rights reserved, Food House.",
        "category" => "Choose category",
        "search" => "Search for food..",
        "search2" => "Search",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => "",
        "" => ""
    );

?>